### ISSUE TITLE
No module named pexpect

### ISSUE THREAD

**Issue by pike084** [KenT2/pipresents-gapless#31]
Hi there,

I followed all the instructions multiple times exactly as they were, however I keep getting an ImportError.

`pi@XXXXXX:~ $ python /home/pi/pipresents/pipresents.py -p pp_mediashow_1p3`
`Traceback (most recent call last):`
`  File "/home/pi/pipresents/pipresents.py", line 40, in <module>`
`    from pp_showmanager import ShowManager`
`  File "/home/pi/pipresents/pp_showmanager.py", line 320, in <module>`
`    from pp_menushow import MenuShow`
`  File "/home/pi/pipresents/pp_menushow.py", line 4, in <module>`
`    from pp_show import Show`
`  File "/home/pi/pipresents/pp_show.py", line 12, in <module>`
`    from pp_audioplayer import AudioPlayer`
`  File "/home/pi/pipresents/pp_audioplayer.py", line 2, in <module>`
`    from pp_mplayerdriver import MplayerDriver`
`  File "/home/pi/pipresents/pp_mplayerdriver.py", line 1, in <module>`
`    import pexpect`
`ImportError: No module named pexpect`

That is the error I keep getting even with the example as you can see.

Have I missed something by chance?

Thanks!! Really looking forward to trying this out! 👍  :)

Josh

**Comment by pike084** [comment]
And I just realised the problem... I hadn't installed pexpect yet...

It's in the PiPresent 1.2 documentation not the 1.3.

All working now :)
