### ISSUE TITLE
can you help me please 

### ISSUE THREAD

**Issue by gayan12** [KenT2/pipresents-gapless#90]
I did follow your instruction and install pipresents-gapless.  But ones I try to run example file this message comes.  I am a new starter for raspberry pi.  also I am using raspbery pi Z w board . can you help me, please . 
Have a nice day
Gayan
    $ python /home/pi/pipresents/pipresents.py -p pp_mediashow_1p3
Traceback (most recent call last):
  File "/home/pi/pipresents/pipresents.py", line 28, in <module>
    from pp_showmanager import ShowManager
  File "/home/pi/pipresents/pp_showmanager.py", line 342, in <module>
    from pp_menushow import MenuShow
  File "/home/pi/pipresents/pp_menushow.py", line 4, in <module>
    from pp_show import Show
  File "/home/pi/pipresents/pp_show.py", line 12, in <module>
    from pp_audioplayer import AudioPlayer
  File "/home/pi/pipresents/pp_audioplayer.py", line 2, in <module>
    from pp_mplayerdriver import MplayerDriver
  File "/home/pi/pipresents/pp_mplayerdriver.py", line 1, in <module>
    import pexpect
ImportError: No module named pexpect

**Comment by KenT2** [comment]
You  missed out

     sudo apt-get install python-pexpect
